name: Lint

on:
  push:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: make init
      - name: Run Linter
        run: make lint