name: CI

on:
  push:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run ruff
        run: poetry run ruff check

  test:
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install --with dev
      - name: Run Tests
        run: poetry run pytest tests