name: CI

on:
  push:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "*.py"
      - "*.toml"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment and install dependencies
      uses: ./.github/actions/setup
      with:
        python-version: "3.10"
    - name: Ruff Check
      run: poetry run ruff check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment and install dependencies
      uses: ./.github/actions/setup
      with:
        python-version: "3.9"
    - name: Ruff Check
      run: poetry run pytest tests